#!/bin/bash


#Creating tip_sentiment directory within the yelp/results directory in Local filesystem
mkdir yelp/results/tip_sentiment

#Creating tip_sentiment_trial directory within the yelp/results/tip_sentiment directory in Local filesystem
mkdir yelp/tip_sentiment_trial_1

